import {
  type Intent,
  type Layout,
  type SlideTemplate,
  type Slot,
  type ThemeId,
  type TemplateStatus,
} from "./domain";

function slot(
  key: string,
  label: string,
  role: Slot["role"],
  maxChars: number,
  x: number,
  y: number,
  w: number,
  h: number,
  fontSize: number,
  required = true,
): Slot {
  return { key, label, role, maxChars, x, y, w, h, fontSize, required };
}
export const layoutSlots: Record<Layout, Slot[]> = {
  hero: [
    slot("eyebrow", "카테고리", "label", 30, 0.065, 0.14, 0.6, 0.06, 24, false),
    slot("title", "핵심 메시지", "title", 44, 0.065, 0.29, 0.76, 0.3, 94),
    slot("body", "설명", "body", 110, 0.07, 0.68, 0.57, 0.15, 29),
  ],
  split: [
    slot("title", "비교 주제", "title", 36, 0.065, 0.08, 0.86, 0.16, 60),
    slot("left_label", "선택 A", "label", 20, 0.09, 0.33, 0.34, 0.08, 35),
    slot("left_body", "선택 A 설명", "body", 130, 0.09, 0.45, 0.34, 0.28, 31),
    slot("right_label", "선택 B", "label", 20, 0.56, 0.33, 0.34, 0.08, 35),
    slot("right_body", "선택 B 설명", "body", 130, 0.56, 0.45, 0.34, 0.28, 31),
  ],
  "metric-grid": [
    slot("title", "지표 제목", "title", 36, 0.065, 0.1, 0.86, 0.16, 60),
    slot("value_1", "첫 번째 값", "value", 12, 0.075, 0.4, 0.245, 0.17, 100),
    slot(
      "label_1",
      "첫 번째 지표",
      "caption",
      25,
      0.075,
      0.62,
      0.245,
      0.12,
      30,
    ),
    slot("value_2", "두 번째 값", "value", 12, 0.39, 0.4, 0.245, 0.17, 100),
    slot("label_2", "두 번째 지표", "caption", 25, 0.39, 0.62, 0.245, 0.12, 30),
    slot("value_3", "세 번째 값", "value", 12, 0.705, 0.4, 0.245, 0.17, 100),
    slot(
      "label_3",
      "세 번째 지표",
      "caption",
      25,
      0.705,
      0.62,
      0.245,
      0.12,
      30,
    ),
  ],
  steps: [
    slot("title", "흐름 제목", "title", 36, 0.065, 0.09, 0.86, 0.17, 60),
    slot("step_1", "첫 번째 단계", "step", 26, 0.085, 0.43, 0.22, 0.16, 43),
    slot(
      "body_1",
      "첫 번째 설명",
      "body",
      70,
      0.085,
      0.63,
      0.22,
      0.16,
      25,
      false,
    ),
    slot("step_2", "두 번째 단계", "step", 26, 0.39, 0.43, 0.22, 0.16, 43),
    slot(
      "body_2",
      "두 번째 설명",
      "body",
      70,
      0.39,
      0.63,
      0.22,
      0.16,
      25,
      false,
    ),
    slot("step_3", "세 번째 단계", "step", 26, 0.695, 0.43, 0.22, 0.16, 43),
    slot(
      "body_3",
      "세 번째 설명",
      "body",
      70,
      0.695,
      0.63,
      0.22,
      0.16,
      25,
      false,
    ),
  ],
  timeline: [
    slot("title", "일정 제목", "title", 36, 0.065, 0.09, 0.86, 0.17, 60),
    slot("label_1", "첫 번째 시점", "label", 18, 0.085, 0.35, 0.22, 0.08, 28),
    slot("step_1", "첫 번째 마일스톤", "step", 45, 0.085, 0.55, 0.22, 0.2, 37),
    slot("label_2", "두 번째 시점", "label", 18, 0.39, 0.35, 0.22, 0.08, 28),
    slot("step_2", "두 번째 마일스톤", "step", 45, 0.39, 0.55, 0.22, 0.2, 37),
    slot("label_3", "세 번째 시점", "label", 18, 0.695, 0.35, 0.22, 0.08, 28),
    slot("step_3", "세 번째 마일스톤", "step", 45, 0.695, 0.55, 0.22, 0.2, 37),
  ],
  editorial: [
    slot("eyebrow", "분류", "label", 24, 0.065, 0.12, 0.45, 0.06, 24, false),
    slot("title", "인사이트", "title", 46, 0.065, 0.28, 0.52, 0.32, 76),
    slot("body", "근거와 설명", "body", 180, 0.65, 0.3, 0.28, 0.42, 31),
  ],
};

const samples: Record<Layout, Record<string, string>> = {
  hero: {
    eyebrow: "MAKE ROOM FOR BETTER IDEAS",
    title: "더 적은 반복,\n더 많은 가능성.",
    body: "아이디어가 디자인이 되기까지.\n좋은 구조에서 더 나은 이야기가 시작됩니다.",
  },
  split: {
    title: "달라지는 디자인 워크플로우",
    left_label: "반복 작업 중심",
    left_body: "템플릿을 하나씩 탐색하고\n내용을 수작업으로 바꿉니다.",
    right_label: "구조 중심",
    right_body: "내용의 의도에 맞는 구조를 찾고\n품질 규칙으로 검수합니다.",
  },
  "metric-grid": {
    title: "숫자에서 발견한 가능성",
    value_1: "40%",
    label_1: "반복 작업 감소",
    value_2: "120",
    label_2: "완성된 콘텐츠",
    value_3: "96%",
    label_3: "브랜드 일관성",
  },
  steps: {
    title: "아이디어에서 완성까지",
    step_1: "내용 이해",
    body_1: "브리프의 핵심 메시지와\n전달 의도를 정리합니다.",
    step_2: "구조 선택",
    body_2: "의도와 내용량에 맞는\n검증된 구조를 찾습니다.",
    step_3: "품질 확인",
    body_3: "레이아웃과 내용의\n완성도를 검토합니다.",
  },
  timeline: {
    title: "작게 시작하고, 함께 확장하기",
    label_1: "발견",
    step_1: "핵심 문제와\n품질 기준 정의",
    label_2: "검증",
    step_2: "작은 실험과\n사용성 확인",
    label_3: "확장",
    step_3: "피드백을 반영한\n제품 고도화",
  },
  editorial: {
    eyebrow: "A DIFFERENT PERSPECTIVE",
    title: "좋은 디자인은\n좋은 구조에서.",
    body: "아름다운 결과물만으로는 충분하지 않습니다.\n\n누가, 왜, 어떤 내용을 전달하려는지 이해하는 것. 그곳에서 디자인의 기준을 찾습니다.",
  },
};

const specs: Array<
  [string, string, Intent, Layout, ThemeId, TemplateStatus, string[]]
> = [
  [
    "atlas-hero-01",
    "아이디어의 시작",
    "overview",
    "hero",
    "coral",
    "approved",
    ["표지", "핵심", "비전", "pitch", "opening"],
  ],
  [
    "atlas-hero-02",
    "대담한 한 문장",
    "overview",
    "hero",
    "midnight",
    "approved",
    ["선언", "메시지", "브랜드", "vision"],
  ],
  [
    "atlas-hero-03",
    "캠페인 오프닝",
    "overview",
    "hero",
    "paper",
    "in_review",
    ["캠페인", "론칭", "발표"],
  ],
  [
    "atlas-split-01",
    "두 가지 선택",
    "comparison",
    "split",
    "coral",
    "approved",
    ["비교", "대조", "장단점", "versus", "compare"],
  ],
  [
    "atlas-split-02",
    "변화의 전과 후",
    "comparison",
    "split",
    "forest",
    "approved",
    ["개선", "변화", "before", "after"],
  ],
  [
    "atlas-split-03",
    "문제와 해결",
    "comparison",
    "split",
    "paper",
    "in_review",
    ["문제", "해결", "problem", "solution"],
  ],
  [
    "atlas-metrics-01",
    "성장을 읽는 숫자",
    "metrics",
    "metric-grid",
    "midnight",
    "approved",
    ["성장", "성과", "KPI", "지표", "매출"],
  ],
  [
    "atlas-metrics-02",
    "임팩트 스코어카드",
    "metrics",
    "metric-grid",
    "coral",
    "approved",
    [
      "임팩트",
      "전환",
      "수치",
      "성과",
      "성장",
      "지표",
      "매출",
      "KPI",
      "metrics",
    ],
  ],
  [
    "atlas-metrics-03",
    "팀의 성과",
    "metrics",
    "metric-grid",
    "forest",
    "draft",
    ["분기", "팀", "리포트"],
  ],
  [
    "atlas-steps-01",
    "생각을 실행으로",
    "process",
    "steps",
    "coral",
    "approved",
    ["프로세스", "단계", "흐름", "워크플로우", "process"],
  ],
  [
    "atlas-steps-02",
    "사용자의 여정",
    "process",
    "steps",
    "forest",
    "approved",
    ["여정", "온보딩", "순서", "journey"],
  ],
  [
    "atlas-steps-03",
    "실험의 루프",
    "process",
    "steps",
    "paper",
    "in_review",
    ["실험", "검증", "학습"],
  ],
  [
    "atlas-timeline-01",
    "다음 장을 향해",
    "timeline",
    "timeline",
    "paper",
    "approved",
    ["로드맵", "일정", "마일스톤", "roadmap", "분기"],
  ],
  [
    "atlas-timeline-02",
    "작게 시작하는 로드맵",
    "timeline",
    "timeline",
    "forest",
    "approved",
    ["계획", "월별", "출시", "일정", "roadmap"],
  ],
  [
    "atlas-timeline-03",
    "프로젝트의 발자취",
    "timeline",
    "timeline",
    "coral",
    "rejected",
    ["히스토리", "일정", "기록"],
  ],
  [
    "atlas-editorial-01",
    "관점을 바꾸는 인사이트",
    "insight",
    "editorial",
    "coral",
    "approved",
    ["인사이트", "관점", "배움", "insight"],
  ],
  [
    "atlas-editorial-02",
    "데이터 너머의 이야기",
    "insight",
    "editorial",
    "midnight",
    "approved",
    ["시사점", "해석", "결론", "인사이트"],
  ],
  [
    "atlas-editorial-03",
    "고객의 목소리",
    "insight",
    "editorial",
    "forest",
    "draft",
    ["인터뷰", "리서치", "인용"],
  ],
];

export const SEED_TEMPLATES: SlideTemplate[] = specs.map(
  ([id, name, intent, layout, defaultTheme, status, tags]) => ({
    id,
    name,
    intent,
    layout,
    defaultTheme,
    status,
    tags,
    description: `${name}에 적합한 ${layout === "hero" ? "낮은" : "중간"} 정보 밀도의 16:9 템플릿. 전달 의도와 슬롯 용량을 함께 정의한 원본 디자인입니다.`,
    density: layout === "hero" ? "low" : "medium",
    slots: layoutSlots[layout].map((s) => ({ ...s })),
    sampleContent: { ...samples[layout] },
    version: 1,
    updatedAt: "2026-08-31T00:00:00.000Z",
  }),
);

export const EXAMPLE_BRIEF = `캠페인 리뷰: 더 적은 반복, 더 많은 가능성.
무브 스튜디오의 디자인 워크플로우 개선 제안입니다.
기존 방식은 템플릿 탐색과 내용 대치에 반복 작업이 많았습니다.
새로운 방식은 의도에 맞는 구조 검색과 자동 품질 검수입니다.
가상 캠페인 결과: 반복 작업 40% 감소, 완성된 콘텐츠 120개, 브랜드 일관성 96%.
진행 과정: 내용 이해 → 구조 선택 → 품질 확인.
다음 단계: 작은 실험에서 얻은 피드백으로 제품을 고도화합니다.
위 숫자는 제품 시연용 가상 데이터이며 실제 고객 성과가 아닙니다.`;

export const SAMPLE_DECK_SLIDES = [
  "atlas-hero-01",
  "atlas-split-01",
  "atlas-metrics-01",
  "atlas-steps-01",
].map((templateId, i) => ({
  id: `sample-slide-${i + 1}`,
  templateId,
  templateVersion: 1,
  values: { ...SEED_TEMPLATES.find((t) => t.id === templateId)!.sampleContent },
  theme: (i === 2 ? "midnight" : "coral") as ThemeId,
}));
